bumbing version to 2023.06 and masking OpenSSL to older than v3.*
EESSI/compatibility-layer pull request #184
Opened 2023-06-07 11:59 UTC by trz42

This is the first attempt to build a new compatibility layer for EESSI.

2023-06-07 12:01 UTC, trz42 commented
Check if the bot is installed for this repository:

bot: help

2023-06-07 18:27 UTC, boegel requested changes

2023-06-07 18:27 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +  <dev-libs/openssl-3
This should be `>=` (see the masking for GCC above)

fixed in https://github.com/trz42/compatibility-layer/pull/2

2023-06-09 14:17 UTC, trz42 commented
Testing updated bot instance:

bot: help
bot: showconfig
bot: build arch:magic inst:cloud

2023-06-15 08:57 UTC, merged

2023-06-15 09:07 UTC, boegel commented
was merged via #188