build compat layer software.eessi.io/2023.06
EESSI/compatibility-layer pull request #191
Opened 2023-09-09 18:38 UTC by trz42

- changed repository name to software.eessi.io
- fixed creation of tarball at the end of `bot/build.sh`
 - should be improved to handle errors when some tmp directory couldn't be determined
- added `bot/check-build.sh` that prepares `.result` file including a status update for the PR comment
- added a bit more debug output in `install_compatibility_layer.sh`, should help with setting up debug sessions

Did not change CI `pilot_repo.yml` yet.

2023-09-09 18:54 UTC, trz42 commented
bot: build arch:generic repo:compat

2023-09-10 06:31 UTC, trz42 commented
The building "worked", the task that failed was the ReFrame test at the end. This tests (among other things) if a `startprefix` under the correct prefix is found. It wasn't. It seems, re-using the repo config (repo name) from `eessi-2023.06-compat` didn't work. The old prefix was used.

Reconfigured the bot to be able to build for two repositories `eessi.org-2023.06-compat` (renamed from `eessi-2023.06-compat`) and `eessi.io-2023.06-compat` (for the new one).

bot: show_config

2023-09-10 06:33 UTC, trz42 commented
bot: build arch:generic repo:eessi.io-2023.06-compat

2023-11-18 10:12 UTC, boegel commented
@trz42 @bedroge This can be merged too now right, since the compat layer has already been ingested (and even package updates have been installed, see #193)?

2023-11-20 10:53 UTC, bedroge requested changes
@trz42  Just two small comments, but other than that I guess it's ready to be merged?

2023-11-20 10:53 UTC, bedroge commented on bot/check-build.sh
> +# tar_topdir=/cvmfs/${eessi_repo}/versions
Can these commented lines be removed?

2023-11-20 10:53 UTC, bedroge commented on bot/check-build.sh
> +# TODO adjust format to what NESSI bot uses
Not sure what needs to happen here, but this mentions NESSI? Can it be removed, or is there still something that needs to be changed?

2023-12-20 19:31 UTC, boegel commented
I prefer to have this merged, to avoid surprises going forward, since this is active in `software.eessi.io/versions/2023.06/compat`.

If any cleanup is still required, it can be done in a subsequent PR...

2023-12-20 19:31 UTC, boegel approved these changes

2023-12-20 19:31 UTC, merged