[WIP] EESSI compatibility layer for next version (2025.01?)
EESSI/compatibility-layer pull request #209
Opened 2024-12-20 15:53 UTC by bedroge

Using 2025.01 for now, not sure if that's going to be final version, but I'm using this to do some test runs/installations.

2024-12-20 15:55 UTC, bedroge commented
First runs went quite well, it failed (as expected) in the step that installs our package set, which we don't have yet for this version. The prefix bootstrap completed without issues though.

2024-12-21 08:50 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +gentoo_git_commit: db21a802e879f713cdb8a80235c5982ca257b63f
Include a comment with some info on why this commit was picked (even if it simply was the latest at the time)

Once your PR to bump Lmod to latest has been merged, we'll have a clear reason...

2024-12-21 08:50 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +  # stick to GCC 11.x; using a too recent compiler in the compat layer may complicate stuff in the software layer,
I would go with at least GCC 13, perhaps GCC 14 (unless that causes trouble to build GCC 13.x in software layer)

2024-12-21 08:51 UTC, boegel commented
> First runs went quite well, it failed (as expected) in the step that installs our package set, which we don't have yet for this version. The prefix bootstrap completed without issues though.

On both `x86_64` and `aarch64`? Shall we also try `riscv64`?

2024-12-24 14:21 UTC, bedroge commented
bot: build arch:generic repo:compat

2024-12-24 14:47 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-03 08:42 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-03 12:25 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-03 15:29 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-03 19:11 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-07 11:04 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-01-10 11:16 UTC, bedroge commented
bot: build arch:aarch64/generic repo:eessi.io-2023.06-compat

2025-01-28 14:41 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-02-13 14:22 UTC, bedroge commented
bot: build arch:aarch64/generic repo:eessi.io-2023.06-compat

2025-02-13 16:08 UTC, boegel requested changes

2025-02-13 16:08 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +eessi_version: "2025.01"
@bedroge Let's bump this to `2025.02`?

```suggestion
eessi_version: "2025.02"
```

2025-02-13 16:08 UTC, boegel commented on install_compatibility_layer.sh
> +VERSION=2025.01
```suggestion
VERSION=2025.02

2025-02-13 16:10 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +eessi_version: "2025.01"
Yes, definitely, though it also requires the set to be renamed/merged. I'll do that first.

2025-02-13 16:11 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +    branch: 2025.01_set
This is not available yet, so I'll make a PR/branch for a 2025.02 set first in the gentoo-overlay repo.

2025-02-13 16:12 UTC, bedroge commented on install_compatibility_layer.sh
> +VERSION=2025.01
This should actually not be set at all, and this is changed in https://github.com/EESSI/compatibility-layer/pull/213/files#diff-f5a03e07ed775318214cf3eea39c31c6b589b82c8069834019ab92e497cb7e2a.

2025-02-14 08:48 UTC, bedroge commented
Don't know what's wrong with the CI, it's segfaulting :open_mouth: :
```
#13 84.92 Setting up gcc (4:10.2.1-1) ...
#13 85.07 Setting up perl (5.32.1-4+deb11u4) ...
#13 85.27 Setting up g++ (4:10.2.1-1) ...
#13 85.50 update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
#13 85.51 Setting up libfontconfig1:arm64 (2.13.1-4.2) ...
#13 85.52 Setting up libgd3:arm64 (2.3.0-2) ...
#13 85.52 Setting up libc-devtools (2.31-13+deb11u11) ...
#13 85.53 Processing triggers for libc-bin (2.31-13+deb11u11) ...
#13 85.58 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#13 85.93 Segmentation fault (core dumped)
#13 85.95 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#13 86.35 Segmentation fault (core dumped)
#13 86.35 dpkg: error processing package libc-bin (--configure):
#13 86.35  installed libc-bin package post-installation script subprocess returned error exit status 139
#13 86.35 Processing triggers for ca-certificates (20210119) ...
#13 86.57 Updating certificates in /etc/ssl/certs...
#13 99.57 0 added, 0 removed; done.
#13 99.57 Running hooks in /etc/ca-certificates/update.d...
#13 99.60 done.
#13 99.69 Errors were encountered while processing:
#13 99.69  libc-bin
#13 99.79 E: Sub-process /usr/bin/dpkg returned an error code (1)
#13 ERROR: process "/bin/sh -c apt-get install -y gcc g++ make diffutils libgmp-dev perl wget" did not complete successfully: exit code: 100
```

2025-02-15 12:01 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +eessi_version: "2025.01"
Done in https://github.com/EESSI/compatibility-layer/pull/209/commits/0b67029beda4bbcc55119dc2140217e2e6e1a668.

2025-02-15 12:02 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
> +    branch: 2025.01_set
Renaming the branch didn't really work, so I'll leave it like this for now. Once we're ready to do the final build, we should merge the PR in gentoo-overlay and use the main branch.

2025-02-15 12:03 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-02-15 18:38 UTC, bedroge commented
Let's see what happens for RISC-V (first time we try this with the bot)...

bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-15 18:51 UTC, bedroge commented
This was not using the right container (should use Debian Sid instead of 11, was already fixed in a `riscv` branch`), let's try again.

bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-15 20:16 UTC, bedroge commented
The `/tmp` filesystem didn't have enough space, trying again with `/var/tmp` (which should have >200GB).

bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-18 12:43 UTC, bedroge commented
Trying again, the bot will now request 3 days for the build job.

bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-20 08:23 UTC, bedroge commented
Haven't looked into the details yet, but it looks like the RISC-V build failed at installing GCC 14 in stage 3 of the bootstrap.

2025-02-20 15:11 UTC, boegel commented
> Haven't looked into the details yet, but it looks like the RISC-V build failed at installing GCC 14 in stage 3 of the bootstrap.

Why GCC 14? We want a slightly older GCC in compat layer?

2025-02-20 15:52 UTC, bedroge commented
> > Haven't looked into the details yet, but it looks like the RISC-V build failed at installing GCC 14 in stage 3 of the bootstrap.
> 
> Why GCC 14? We want a slightly older GCC in compat layer?

That's a good question... I'm not sure if we had discussed this in a meeting, but this PR has been using GCC 14 for a while (by masking `GCC >= 15`). Let me mask `>= 14` and try again in parallel to the manual build (as I'd still like to know why 14 doesn't work).

2025-02-20 15:55 UTC, bedroge commented
bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat
bot: build arch:aarch64/generic repo:eessi.io-2023.06-compat

2025-02-20 15:57 UTC, bedroge commented
bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-20 16:48 UTC, boegel commented
> > > Haven't looked into the details yet, but it looks like the RISC-V build failed at installing GCC 14 in stage 3 of the bootstrap.
> > 
> > 
> > Why GCC 14? We want a slightly older GCC in compat layer?
> 
> That's a good question... I'm not sure if we had discussed this in a meeting, but this PR has been using GCC 14 for a while (by masking `GCC >= 15`). Let me mask `>= 14` and try again in parallel to the manual build (as I'd still like to know why 14 doesn't work).

I would at least stick to GCC 13.x, to avoid trouble if we do end up having to installed pre-2024a toolchains in this new EESSI version (though that's not the plan currently)

2025-02-23 08:25 UTC, bedroge commented
> New job on instance `eessi-bot-riscv` for CPU micro-architecture `riscv64-generic` for repository `riscv.eessi.io-20240402` in job dir `/home/eessibot/shared/jobs/2025.02/pr_209/223568`
> 
> date	job status	comment
> Feb 20 15:57:35 UTC 2025	submitted	job id `223568` awaits release by job manager
> Feb 20 15:57:46 UTC 2025	released	job awaits launch by Slurm scheduler
> Feb 20 15:58:50 UTC 2025	running	job `223568` is running
> Feb 23 00:43:48 UTC 2025	finished	
> 😢 FAILURE _(click triangle for details)_
> Feb 23 00:43:48 UTC 2025	test result	
> 😢 FAILURE _(click triangle for details)_

The very last (test) step of the playbook failed, because ReFrame could not be installed:
```
cargo build --manifest-path Cargo.toml --message-format=json-
render-diagnostics --release -v --no-default-features --locked\n            error: package `clap v4.5.7` cannot be built because it requires rustc 1.74 or newer, while the curr
ently active rustc version is 1.70.0\n            Either upgrade to rustc 1.74 or newer, or use\n            cargo update -p clap@4.5.7 --precise ver\n            where `ver` i
s the latest version of `clap` supporting rustc 1.70.0\n            error: `cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v --no-de
fault-features --locked` failed with code 101\n            [end of output]\n      \n        note: This error originates from a subprocess, and is likely not a problem with pip.
\n        ERROR: Failed building wheel for maturin\n      Failed to build maturin\n      ERROR: Failed to build installable wheels for some pyproject.toml based projects (matur
in)\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: subprocess-exited-with-error\n\n× pip subprocess 
to install build dependencies did not run successfully.\n│ exit code: 1\n╰─> See above for output.\n\nnote: This error originates from a subprocess, and is likely not a problem
 with pip.\n"
```

2025-02-27 14:25 UTC, bedroge commented
bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-02-27 14:47 UTC, bedroge commented
bot: build repo:riscv.eessi.io-20240402 arch:riscv64/generic

2025-06-06 21:26 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-06-07 09:09 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
>    # only install Python 3.11
Comment is outdated, and why don't we use Python 3.13 (no problem for EasyBuild 5.x)?

2025-06-07 09:10 UTC, boegel commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
>  prefix_user_defined_trusted_dirs:
Does order matter here? Is the first entry in this list also the first one that's considered (so it is effectively the "override" path)?

2025-06-07 09:11 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
>    # only install Python 3.11
Was just looking into this, I think this actually caused the failure, because some Python packages were installed for the wrong version. Changed this to 3.13.

2025-06-07 09:13 UTC, bedroge commented on ansible/playbooks/roles/compatibility_layer/defaults/main.yml
>  prefix_user_defined_trusted_dirs:
They are passed in that order to glibc (https://github.com/EESSI/compatibility-layer/blob/main/ansible/playbooks/roles/compatibility_layer/tasks/set_glibc_trusted_dirs.yml#L16), so I would hope/expect that the order matters, but I'll see if I can check that once the build has successfully completed.

2025-06-07 09:14 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-06-07 13:14 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-06-07 18:56 UTC, bedroge commented
bot: build arch:x86_64/generic repo:eessi.io-2023.06-compat

2025-06-08 11:15 UTC, bedroge commented
bot: build arch:aarch64/generic repo:eessi.io-2023.06-compat

2025-06-09 18:23 UTC, bedroge commented
bot: build repo:eessi.io-2025.06-compat arch:riscv64/generic

2025-06-09 21:00 UTC, bedroge commented
bot: build repo:eessi.io-2025.06-compat arch:riscv64/generic

2025-06-10 14:13 UTC, bedroge commented
Triggering a final build for all architectures:

bot: build repo:eessi.io-2025.06-compat arch:aarch64/generic
bot: build repo:eessi.io-2025.06-compat arch:riscv64/generic
bot: build repo:eessi.io-2025.06-compat arch:x86_64/generic

2025-06-13 12:12 UTC, bedroge commented
Deploy failed because the container used for building compat layers does not include the deployment tools (`awscli`, `jq`, `curl`). That was fixed in #219.
The RISC-V tarball was deployed, but it was not signed due to wrong permissions on the key. That was manually fixed.

Trying again...

2025-06-13 12:33 UTC, bedroge commented
Failed again: x86_64 and aarc64 were using the wrong version of the container (`debian11` instead of `debian-11`), RISC-V probably had a syntax error in the `app.cfg`. Trying again...

2025-06-13 15:47 UTC, boegel commented
staging PRs merged...

2025-06-13 15:47 UTC, boegel approved these changes

2025-06-13 16:28 UTC, boegel commented
Deployed, so merging!

```
$ ls /cvmfs/software.eessi.io/versions/2025.06/compat/linux/
aarch64/ riscv64/ x86_64/
```

2025-06-13 16:28 UTC, merged