Automatically build and publish the container image for bootstrapping Gentoo Prefix
EESSI/compatibility-layer pull request #98
Opened 2021-04-28 11:04 UTC by bedroge

This action builds a multi-arch Docker image and pushes it to the Github Container Registry.
I've also adjusted our Ansible role, so that it pulls the image from the GCR.

2021-04-28 11:07 UTC, bedroge commented
The tests are failing due to an issue with one of our workflows, this is fixed in #97.

2021-06-19 13:46 UTC, boegel requested changes

2021-06-19 13:46 UTC, boegel commented on .github/workflows/build-and-publish-bootstrap-container.yml
> +          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
I would use double quotes here, which makes this a bit easier to parse (for humans):

```suggestion
          echo "REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

2021-06-19 15:22 UTC, boegel commented
@bedroge Do you understand why CI is failing now?

2021-06-19 18:40 UTC, bedroge commented
These issues have been fixed in another PR, so this PR probably needs to be synced with `main`.

2021-06-20 07:31 UTC, boegel commented
@bedroge CI is still failing :-/

2021-06-20 07:36 UTC, bedroge commented
```
/tmp/gentoo/var/db/repos/eessi/sys-cluster/reframe/reframe-3.6.2.ebuild", " * Reason: Filesize does not match recorded size", " * Got: 969", " * Expected: 1040"
```

Looks like we added a wrong checksum...

2021-06-22 07:22 UTC, bedroge commented
CI for the installation playbook is broken, see #111, let's fix that later (not really related to anything from this PR anyway)...

2021-06-22 07:41 UTC, boegel approved these changes

2021-06-22 07:41 UTC, merged